/*
Author: Dan Gabbay
Date: Dec. 31, 2023

Description:
This computer program generates a random permutation of 'n' different elements,
where 'n' must be in the range of 1 to 10000.

Example ('n' is 10 in this case):
>permut.exe 10<CR>
*/

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define MAXIMUM_DIFFERENT_ELEMENTS 10000

static unsigned short generateRandom(unsigned short range);
static void remove_element_from_list(short index);
static void InitializeListOfElements(short num_of_elements);
static void print_permutation(short number_of_different_elements);

short pointerToFirstElement = 0, pointerToElement;
short rand_val, i, j;

/* An element of a doubly linked list */
typedef struct tag_name {
    short val;
    short next;
    short prev;
} element;

element list_of_elemets[MAXIMUM_DIFFERENT_ELEMENTS];
unsigned short permutation[MAXIMUM_DIFFERENT_ELEMENTS];
unsigned short histogram[MAXIMUM_DIFFERENT_ELEMENTS];

int main(int argc, char* argv[])
{
    short number_of_different_elements = 10000, number_of_different_elements_left = 0;

    unsigned char permutation_is_valid = 1;

    if (argc != 2)
    {
        printf("Number of arguments is incorrect!\n");
        exit(1);
    }
    number_of_different_elements = atoi(argv[1]);
    if ((number_of_different_elements < 1) || (number_of_different_elements > 10000))
    {
        printf("\nArgument is out of range, must be in the range of 1 to 10000.\n");
        exit(1);
    }
    InitializeListOfElements(number_of_different_elements);
    printf("/*\n");
    printf("The table below represents a unique permutation of %d different elements.\nThis permutation was generated by a special utility and must never be modified manually.\n", number_of_different_elements);
    printf("UNIX Time stamp: %d", (int)time(NULL));
    printf("\n*/\n\n\n");
    number_of_different_elements_left = number_of_different_elements;
    for (i = 0; i < MAXIMUM_DIFFERENT_ELEMENTS; i++)
    {
        histogram[i] = 0;
    }

    printf("const unsigned short uniqueValidPermutation[%d] = {\n", number_of_different_elements);
    j = 0;
    while (pointerToFirstElement != -1) // Keep going as long as the list is not empty.
    {
        rand_val = 0;
        if (number_of_different_elements_left > 0)
        rand_val = generateRandom(number_of_different_elements_left);
        number_of_different_elements_left--;
        pointerToElement = pointerToFirstElement;

        for (i = 0; i < rand_val; i++)
        {
            pointerToElement = list_of_elemets[pointerToElement].next;
        }

        permutation[j] = list_of_elemets[pointerToElement].val;
        histogram[list_of_elemets[pointerToElement].val]++;
        j++;
        remove_element_from_list(pointerToElement);
    }

    i = 0;
    while ((i < number_of_different_elements) && (permutation_is_valid == 1))
    {
        if (histogram[i] != 1) permutation_is_valid = 0;
        i++;
    }

    if (permutation_is_valid == 1)
    {
        print_permutation(number_of_different_elements);
        return 0;
    }
    else
    {
        printf("Permutation is not valid, something went wrong!\n");
        return -1;
    }
}


static void print_permutation(short number_of_different_elements)
{
    short i;
    short j;

    j = 1;
    for (i = 0; i < number_of_different_elements - 1; i++)
    {
        printf("%d, ", permutation[i]);
        if ((j % 20) == 0)
        {
            printf("\n");
        }
        j++;
    }
    printf("%d\n};\n", permutation[i]);
}

/*
Description:
This function initializes a doubly linked list with a specific number of elements.
Function name: InitializeListOfElements()
Input parameters:
num_of_elements - Number of elements in the list.
Return:
None
*/

static void InitializeListOfElements(short num_of_elements)
{
    short i;
    pointerToFirstElement = 0;
    for (i = 0; i < num_of_elements; i++)
    {
        list_of_elemets[i].next = i + 1;
        list_of_elemets[i].prev = i - 1;
        list_of_elemets[i].val = i;
    }
    if (num_of_elements <= MAXIMUM_DIFFERENT_ELEMENTS)
    {
        list_of_elemets[num_of_elements - 1].next = -1;
    }
}

/*
Description:
This function removes an element from a doubly linked list stored in an array.
Function name: remove_element_from_list()
Input parameters:
index - Pointer to the element to be removed from the list.
Return:
None
*/

static void remove_element_from_list(short index)
{
    if (index == pointerToFirstElement) // We want to remove the first element in the list.
    {
        pointerToFirstElement = list_of_elemets[index].next;
    }
    else
    if (list_of_elemets[index].next == -1)  // We want to remove the last element in the list
    {
        if (index == pointerToFirstElement) // There is only one element in the list
        {
            pointerToFirstElement = -1;     // The list is now empty.
        }
        else
        {
            list_of_elemets[list_of_elemets[index].prev].next = -1; // The last element in the list was removed but the list is not empty.
        }
    }
    else
    {
        // We want to remove an element in the middle.
        list_of_elemets[list_of_elemets[index].next].prev = list_of_elemets[index].prev;
        list_of_elemets[list_of_elemets[index].prev].next = list_of_elemets[index].next;
    }


}

/*
Description:
This function generates a random number in the range of 0 to "range - 1".
Function name: generateRandom()
Input parameters:
range - a number that determines the range, 0 to "range - 1". Must be greater than zero.
Return:
A random number within the specified range.
*/

static unsigned short generateRandom(unsigned short range)
{
    static char first_time = 1;
    if (first_time == 1)
    {
        first_time = 0;
        srand((unsigned int)time(NULL));
    }
    return rand() % range;
}
